FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY server.py .
COPY server_lib.py .
COPY database.py .
COPY scripts.sql .

COPY storage ./storage

EXPOSE 5000

CMD ["python", "server.py"]