FROM python:3.11-slim

WORKDIR /app

# Install necessary system utilities
RUN apt-get update && apt-get install -y \
    procps \
    iproute2 \
    wireless-tools \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY client.py client_lib.py ./

CMD ["python", "client.py"]
