services:

  server:
    build:
      context: .
      dockerfile: Dockerfile.server

    container_name: network-scanner-server

    ports:
      - "5000:5000"

    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=network_scanner
      - DB_USER=scanner
      - DB_PASSWORD=scanner_password
    volumes:
      - ./storage/log_storage:/app/storage/log_storage

    depends_on:
      mysql:
        condition: service_healthy

    stdin_open: true
    tty: true


  client:
    build:
      context: .
      dockerfile: Dockerfile.client

    container_name: network-scanner-client

    depends_on:
      - server

    restart: unless-stopped


  mysql:
    image: mysql:8.4

    container_name: network-scanner-mysql

    environment:
      MYSQL_DATABASE: network_scanner
      MYSQL_USER: scanner
      MYSQL_PASSWORD: scanner_password
      MYSQL_ROOT_PASSWORD: root_password

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "scanner",
          "-pscanner_password"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  mysql_data: